### ISSUE TITLE
No Aluminum for Tinkers Construct

### ISSUE THREAD

**Issue by PeteJoison** [DoughnutServers/DonutCraftATL#10]
0.0.6c: Can't progress very far with Tinkers Construct because there's no aluminum ore in any of the mods. Need aluminum to smelt Alumite. Need Alumite tools to mine ores to make the Manyullyn OP weapons.

**Comment by mjctechguy** [comment]
You don't get Aluminum unless another mod adds aluminum ore etc. It was a change from the previous version of Tinker Construct this would be the same for all the other ores and metal combos.

**Comment by DoughnutDev** [comment]
Yeah alumite was removed in 1.10. Obsidian should be able to mine cobalt
and ardite.
