### ISSUE TITLE
client crash breaking crafting station/basin - 2 players / countries / times

### ISSUE THREAD

**Issue by Tessellry** [DoughnutServers/DonutCraftATL#16]
AT DonutCraft Version 1.10.2/0.0.9b
http://pastebin.com/4sjq0ijf

Regarding Tinkers Construct: 
Breaking crafting station and casting basin (smelter). Used different pickaxes and materials: minecraft/ TechReborn/Tinkers with the same result - immediate crash.  Consequently "breaking execution".
First happend to a player from another country (working station) at least 1 hour before me (basin).
Also the basin registers as a casting table - not a basin-  as it is placed.

**Comment by DoughnutDev** [comment]
Fixed in next updated. (Not released yet.)

**Comment by DoughnutDev** [comment]
Should be fixed.
