### ISSUE TITLE
Breaking Tinkers crafting station. Wrong labelling hovering over items.

### ISSUE THREAD

**Issue by Tessellry** [DoughnutServers/DonutCraftATL#17]
Breaking Tinkers Crafting Station still are not possible and crashes server (despite update c). 
Labelling of items are also still wrong when hovering over them. Some examples : Silver chest labelled Iron. Metallurgic Infuser labelled Enrichment chamber. Casting basin labelled Casting table aso...

**Comment by DoughnutDev** [comment]
Should be fixed in latest version.
