### ISSUE TITLE
Server crash when starting server after updating from 0.1.0d to 0.1.0f

### ISSUE THREAD

**Issue by Ozimundis** [DoughnutServers/DonutCraftATL#19]
Running a private server through Creeperhost.
Tried to update from version d to version f today, installation went fine but when starting the server, got what at first seemed like an unspecified error, but after talking with the staff at ch, the server was crashing due to Extra Utilities 2. 
This is the crash that the server was throwing up
http://pastebin.com/d4ZXmnBR

Was advised to try and make a new world and try launching the pack, to see if it would launch.
It does.

**Comment by DoughnutDev** [comment]
Okay go into the configuration folder and find Extra Utilities and disable
the Chunk Ward it is near the top of file. Then restart your server this
may cause you do a ./fml confirm in console. So if the console freezes you
will need to this. Let me know if this helps.

I would have this fixed but for some reason you can not disable it on
client without it crashing only the server configurations for Extra
Utilities works.

**Comment by Ozimundis** [comment]
Will do. I've re-generated our world, so we've lost our old world, but I'll make a point to do it for our new instance.
