### ISSUE TITLE
CTD and recipe conflict w/ architecture craft chisel+Pam's Skillet

### ISSUE THREAD

**Issue by Ozimundis** [DoughnutServers/DonutCraftATL#22]
Trying to craft chisel from architecture craft, but Pam's skillet show's up and the moment the recipe is "Complete" In the table, eg, all items are placed in correct position, Minecraft locks up and CTD's

[Also, semi-relevant, Pam's does not appear in JEI Or seem to be recognized by WAILA, none of the items show up in the sidebar and when you have a recipe that can use them, mousing over doesn't have any tooltip. Not sure if this is intentional or not. ]

Error log from CTD
http://pastebin.com/K4TDTG7F

**Comment by DoughnutDev** [comment]
This has been fixed for the next release.
