### ISSUE TITLE
"Save loops"

### ISSUE THREAD

**Issue by Omen267901** [DoughnutServers/DonutCraftATL#23]
Basically, I've been getting stuck in "save loops". What happens is that if I die at any point, or after about 1.5-2 hours of playing the game will start autosaving over and over again. It'll literally go less than a second after autosaving and it'll autosave again. This continues happening until I fully restart the game.

I have added BetterFPS and Optifine to the pack, but this was happening before adding either, as well as with only having BetterFPS.

here is an atl Log:http://paste.atlauncher.com/view/ee21c582

**Comment by DoughnutDev** [comment]
How much ram do you have in the pack?

**Comment by Omen267901** [comment]
4 GB. I haven't tried playing the pack in multiplayer yet, but this definitely happens in singleplayer no matter what.

**Comment by DoughnutDev** [comment]
This maybe due to a hardware issue because when playing singleplayer you are technically running a server only you can join and if you have not very good hardware it will do this.

**Comment by Omen267901** [comment]
I'll post some hardware specs (in form of DxDiag):
[DxDiag.txt](https://github.com/DoughnutServers/DonutCraftATL/files/442776/DxDiag.txt)

**Comment by DoughnutDev** [comment]
This issue should be fixed in 2.0.0 not sure what is going on in the previous versions.
