### ISSUE TITLE
intermittent Serverside Crash

### ISSUE THREAD

**Issue by Ozimundis** [DoughnutServers/DonutCraftATL#24]
http://pastebin.com/qMQHS5HW

Not sure what's causing the crash, one of our players has just told me that it crashed as he looked in a specific direction
"the game loaded for me, and i could walk around, then i looked up and it crashed"
http://pastebin.com/KMc7SuE8 Crash repo from the above action.

**Comment by Ozimundis** [comment]
And another, this time, the player was looking at his feet, the entire time. 
http://pastebin.com/ZSq0nqmU

**Comment by DoughnutDev** [comment]
Are you using the configs included in the pack download?

**Comment by Ozimundis** [comment]
Yes, that was pack version 0.1.0d, since updating to 0.1.1b it seems to have been fixed.
