### ISSUE TITLE
Donutcraft 0.1.1b crashes upon initialisation

### ISSUE THREAD

**Issue by Zeemo** [DoughnutServers/DonutCraftATL#26]
Hi there,
So I downloaded the pack, fresh install, upon first launch the pack hung for quite some time on Reloading - Model Manager, and being as patient as I was, I waited 5 minutes to let it do it's thing.
5 minutes are up, and the pack just closes, I did get a crash report though, it's a Java heap space error.
Here is the report:
[crash-2016-08-26_22.59.24-client.txt](https://github.com/DoughnutServers/DonutCraftATL/files/439962/crash-2016-08-26_22.59.24-client.txt)
[Pastebin form.](http://pastebin.com/swjWRc5j)

I have 3 GB of RAM allocated and it should be more than enough to launch this pack.
Thank you for your support.

**Comment by DoughnutDev** [comment]
Have you tried reinstalling.

**Comment by Zeemo** [comment]
Yes, I get the same error.

**Comment by DoughnutDev** [comment]
Are you running Java 8 64-bit
