### ISSUE TITLE
[2.0.0-OPEN_BETA] [BUG] [Tinker's Construct] Lumbering Axe does not work in overworld.

### ISSUE THREAD

**Issue by reihned** [DoughnutServers/DonutCraftATL#28]
Originall brought up by darkjedibrad on discord,

> darkjedibrad: lumber ax from tinkers will not chop down trees  when i go to do it the breaking shows then it goes back to normal

I've been able to reproduce it in the overworld. Lumbering Axe does not work.

However: 
- within Aroma's mining dimension the Lumbering Axe works fine.
- other tinker's axes such as the hatchet and mattock also work fine.

**Comment by reihned** [comment]
on suggestion from PathMaker (discord) Tinker's Construct Hammer and Excavator work fine.

**Comment by DoughnutDev** [comment]
Should be fixed in 2.0.0-005
