### ISSUE TITLE
[Tinker's alloy addon] Mending moss incompatable

### ISSUE THREAD

**Issue by sstarnes3** [DoughnutServers/DonutCraftATL#33]
Tools which use metal from tinker's alloy addon can not be repaired by mending moss. Most notably vibranium and adamantium. (Not sure if this is a bug or intentional)

**Comment by sstarnes3** [comment]
With some extra testing it appears that possibly base tools from tinker's construct could also be afftected

**Comment by DoughnutDev** [comment]
This should be fixed now in 2.0.0-005
