### ISSUE TITLE
Can't even start up newest version.

### ISSUE THREAD

**Issue by Omen267901** [DoughnutServers/DonutCraftATL#35]
Newest version of the pack is closing after attempting to launch. Barely gets 1/10 of the way to loading and boots back to launcher.

http://paste.atlauncher.com/view/66f5eaed

**Comment by sstarnes3** [comment]
The pack has been updated to 2.0.0-004, try it now. If it still doesn't work make sure your java is up to date. If it works, close this thread please.

**Comment by Omen267901** [comment]
Nope, not fixed. http://paste.atlauncher.com/view/d77d2296

**Comment by DoughnutDev** [comment]
Please delete the pack and totally reinstall it.

**Comment by ryu2065** [comment]
I have done this and am still getting the same crash.

**Comment by DoughnutDev** [comment]
Can you please provide me with a crash log?

**Comment by Omen267901** [comment]
I'm going somewhere for the weekend, so I can't do anything until then.
