### ISSUE TITLE
Broken botania flowers

### ISSUE THREAD

**Issue by sstarnes3** [DoughnutServers/DonutCraftATL#42]
Reysol found some botania flowers with broken textures. Picking up these flowers gives the player a poppy but mousing over said flower in the inventory screen crashes the client.

Using f3 I've found it's called botania:specialFlower. In the hand it's called tile.botania:null.name

I've left the flowers in the world if someone wants to take a closer look.
![2016-09-25_16 12 27](https://cloud.githubusercontent.com/assets/20386830/18817994/ae1935ac-833b-11e6-8d2a-7ac7d24bb7f6.png)
![2016-09-25_16 12 35](https://cloud.githubusercontent.com/assets/20386830/18817997/b4163cf2-833b-11e6-8dd4-bc3b3a840d2b.png)

**Comment by DoughnutDev** [comment]
Fixed
