### ISSUE TITLE
Storage Drawers not protected

### ISSUE THREAD

**Issue by sstarnes3** [DoughnutServers/DonutCraftATL#43]
The drawers from the mod Storage Drawers are not protected via chunk claiming. They require the personal key to truely protect them.

This could be a good thing, as it adds a way for players to interact on their bases without losing block breaking protection. It's up to you donughnutdev whether or not you want to fix this.

**Comment by DoughnutDev** [comment]
I myself can not fix this issue this is a FTBUtil issue.

**Comment by DoughnutDev** [comment]
Possibly fixed
