### ISSUE TITLE
Got full stack of Creosote Bottle when crafting

### ISSUE THREAD

**Issue by Cagari** [DoughnutServers/DonutCraftATL#53]
Was using Creosote Bottle (Railcraft) to craft Treated Wood planks. When I shift clicked the treated wood on a crafting station. I got the wood and the Creosote bottle turned into a stack of 64.

*Edit  Happed twice in a row.

**Comment by mjctechguy** [comment]
Think it better to disable to use of creosote bottles from Railcraft and the creation of the oil from the furnace

**Comment by mjctechguy** [comment]
https://github.com/DoughnutServers/DonutCraftATL/pull/57
