### ISSUE TITLE
RFtools

### ISSUE THREAD

**Issue by Tessellry** [DoughnutServers/DonutCraftATL#6]
RFTOOLS
DIMLET ESSENCE: Been struggeling hours creating rftools dimlets. For example Peaceful - couldnt get it done either with the essence item (taken from creative mode ) or manually by doing it with 9 syringes of specific mobs blod - neither worked. Attn: The zombie pigmens blood registers as a common zombie.
No one of the creative structure essence items work either (Dungeon, Fortress aso)... Placed them in the last "dropshape" slot in the workbench... maybe Im doin it wrong but isnt they supposed 2 be placed there ? Every other part is correct but nothing happens no matter what essence is added. 

WRENCH: Sneak right klicking doesnt pick up the machine and only right klicking causes an immediate crash every time no matter what machine is klicked at.  The message is "shutting down internal server". 

Theres a lot changed since I last played Rftools so I hope I havent mentioned something in vain.

**Comment by Tessellry** [comment]
Other experience the same result regarding the rftools wrench. They crash and get thrown out over and over again when they wrench frtools machines so cant be just ONE client bug in that case

**Comment by DoughnutDev** [comment]
This should be fixed in 0.0.9
